{{- if .Values.provider.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.provider.secret.name }}
data:
  serviceAccountJSON: {{ .Values.serviceAccountJSON }}
  folderID: {{ .Values.folderID }}
  vpcID: {{ .Values.vpcID }}
  routeTableID: {{ .Values.routeTableID }}
{{- end }}
