---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-lifecycle.{{ .Values.providerName }}-{{ include "cluster-machine-controller.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-lifecycle.{{ .Values.providerName }}-{{ include "cluster-machine-controller.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.providerName }}-{{ include "cluster-machine-controller.name" . }}
  namespace: {{ .Release.Namespace }}
