---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: machine-class.{{ .Values.providerName }}-{{ include "cluster-machine-controller.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: machine-class.{{ .Values.providerName }}-{{ include "cluster-machine-controller.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.providerName }}-{{ include "cluster-machine-controller.name" . }}
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: botstrap-tokens.{{ .Values.providerName }}-{{ include "cluster-machine-controller.name" . }}
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: botstrap-tokens.{{ .Values.providerName }}-{{ include "cluster-machine-controller.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.providerName }}-{{ include "cluster-machine-controller.name" . }}
  namespace: {{ .Release.Namespace }}