{{- if .Values.provider.secret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.provider.secret.name }}
type: Opaque
data:
  serviceAccountJSON: {{ .Values.serviceAccountJSON }}
  folderID: {{ .Values.folderID }}
{{- end }}
